name: my-workflow
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name : print some random message
        run : echo "some random message"
      - name : Checkout code
        uses : actions/checkout@v2
